# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7870bdba1fe0300aa96107b36b2f89395fdb9cdb9909d5e34b88ca488060e812dfee39993c314d62568ecdc994c50297e3cdd258336622304195b831254e4806

test:
  secret_key_base: 6eeb4b7b5d71523529ab5fb155bfc9a3a5b390c443c4e17b887ea1092b4631eb9ecfc2e9a807e0c9ab9add3c97e79505d24fcb8ae20cad1a3a6dc44852c892e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
